### ISSUE TITLE
geojson rows missing from sqlite distributions

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/go-whosonfirst-sqlite-index#1]
The continent of Asia is not present in the `geojson` table, but it is available in the `spr` table:

```bash
sqlite> select * from geojson where id = 102191569;

sqlite> select * from spr where id = 102191569;
102191569||-4251112170830360571|multipolygon|XX||34.5444195|0.0|-12.199965|-180.0|34.5444195|180.0|-1|-1|-1|-1|-1|||-1
```

Further checking of the `whosonfirst-data-admin-xy-latest.db` database reveals that this is not the only record missing:

```bash
sqlite> SELECT COUNT(*) FROM geojson;
16052

sqlite> SELECT COUNT(*) FROM spr;
18572

sqlite> SELECT COUNT(*) FROM spr LEFT JOIN geojson USING(id) WHERE geojson.id IS NULL;
2520
```

I downloaded `whosonfirst-data-admin-us-latest.db` to check if it was an isolated issue, unfortunately, it isn't:

```bash
sqlite> SELECT COUNT(*) FROM geojson;
234651

sqlite> SELECT COUNT(*) FROM spr;
273935

sqlite> SELECT COUNT(*) FROM spr LEFT JOIN geojson USING(id) WHERE geojson.id IS NULL;
39284
```

**Comment by missinglink** [comment]
I think I've tracked down the issue:

- https://github.com/whosonfirst/go-whosonfirst-sqlite-features/blob/master/tables/geojson.go#L129
- https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go#L276-L283

Is seems that since the continent of Asia has a parent of `-1` is it being considered `'alt'` and then not included in the distributions.

https://spelunker.whosonfirst.org/id/102191569/

I haven't confirmed if this is the issue for all of the omissions but its a good start.

**Comment by missinglink** [comment]
This is the source of the bug https://github.com/whosonfirst/go-whosonfirst-geojson-v2/commit/b343f334e850c6f7b300df6e51b367bd7f937135

It was committed directly to master without any context of what it was related to, not sure why the `spr` table doesn't have a similar check: https://github.com/whosonfirst/go-whosonfirst-sqlite-features/blob/master/tables/spr.go#L124

**Comment by straup** [comment]
• https://github.com/whosonfirst/go-whosonfirst-geojson-v2/issues/4
• https://github.com/whosonfirst/go-whosonfirst-sqlite-features/issues/6
• https://github.com/whosonfirst/go-whosonfirst-dist/issues/13

**Comment by straup** [comment]
```
{
  "name": "whosonfirst-data-admin-xy-latest.db",
  "type": "x-urn:whosonfirst:database:sqlite#common",
  "name_compressed": "whosonfirst-data-admin-xy-1566247580.db.bz2",
  "count": 18572,
  "size": 171360256,
  "size_compressed": 42772089,
  "sha256_compressed": "eb9f083a34c4aaede37604697ffd82d40a00c7e0cc94af84a5c238fb95b3e913",
  "last_updated": "2019-08-19T20:46:20Z",
  "last_modified": "2019-08-23T03:27:13Z",
  "repo": "whosonfirst-data-admin-xy",
  "commit": "217cbe0a641365995009455960bf097cab1cb9a6"
}

$> wget https://dist.whosonfirst.org/sqlite/whosonfirst-data-admin-xy-latest.db.bz2
$> bunzip2 whosonfirst-data-admin-xy-latest.db.bz2 
$> sqlite3 whosonfirst-data-admin-xy-latest.db 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> SELECT id FROM geojson WHERE id=102191569;
102191569
```
